---
url: "http://hmg.com.br"
database: 
  host: "192.168.99.120"
  dbname: "nflix"
  user: "postgres"
  password: "qaninja"
users: 
  cat_manager:
    email: "tony@stark.com"
    pass: "123456"
    
    